spring.application.name=retail-store-api
server.port=${PORT:8080}

# MySQL DataSource (Aiven Cloud)
spring.datasource.url=jdbc:mysql://retail-db-rajaadhikary05032005-0e89.c.aivencloud.com:26009/defaultdb?useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# CORS (allow frontend)
app.cors.allowed-origins=http://localhost:5173,https://retail-store-gilt.vercel.app

